name: NPM Publish (RELEASE)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish-release:
    name: Build/Publish (RELEASE)
    environment:
      name: RELEASE
      url: https://www.npmjs.com/package/linted?activeTab=versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Install Node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - name: Update NPM
        id: npm
        run: npm i -g npm
      - name: Install Dependencies
        id: ci
        run: npm ci
      - name: Publish to NPM
        id: publish
        run: npm publish
        env: { NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}" }
